### PR TITLE
Fix broken error message when applying manifests

### LINKED ISSUE #5689: Broken error message
**What would you like to be added**:

We got this message while applying our deployment. It seems PipeCD codebase is using a wrong Go string format at that log entry.

```
Failed to apply manifest: name="foo", kind="Deployment", namespace="foo", apiVersion="apps/v1" (%!w(*fmt.wrapError=&{failed to apply
```

**Why is this needed**:

### PR DESCRIPTION
**Pull request by dvcanton**
**What this PR does**:
Fix format verb for error messages when applying a manifest.

**Why we need it**:

**Which issue(s) this PR fixes**:
Fix #5689

Fixes #

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

File: pkg/app/piped/executor/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -277,7 +277,7 @@ func applyManifests(ctx context.Context, ag applierGetter, manifests []provider.
 		}
 
 		if err := applier.ApplyManifest(ctx, m); err != nil {
-			lp.Errorf("Failed to apply manifest: %s (%w)", m.Key.ReadableString(), err)
+			lp.Errorf("Failed to apply manifest: %s (%v)", m.Key.ReadableString(), err)
```
Comment (khanhtc1202) [inline pkg/app/piped/executor/kubernetes/kubernetes.go:280]:
```suggestion
			lp.Errorf("Failed to apply manifest: %s (%w)", m.Key.ReadableString(), err.Error())
```
I think this is what we're expecting here 👀 `%w` is for error format, the issue is instead of passing the err itself to persister, just pass the Error message of the error. Same for the other.

**Review by khanhtc1202 — APPROVED** [review]
Nice catch, thank you 👍

**Review by Warashi — APPROVED** [review]
LGTM
