### PR TITLE
Fix ECS rollback stage does not remove canary created tasks

### LINKED ISSUE #4329: [ECS] Cancel with rollback does not remove canary created tasks
**What happened**:

While deploying ECS applications with canary-related stages, cancel with rollback command does revert the application version to the previous one but doesn't remove canary stage created tasks. The reason due to canary stage created and connected canary tasks to the LB target group, and that keeps those tasks available to handle requests to that target group

**What you expected to happen**:

Remove canary stages created task on deployment cancel

**How to reproduce it**:

**Environment**:
- `piped` version: v0.43.0
- `control-plane` version: v0.43.0
- Others:

### PR DESCRIPTION
**Pull request by ductnn**
**What this PR does / why we need it**:

- Fix `Cancel with rollback` does not remove canary created tasks

**Which issue(s) this PR fixes**:

Fixes #4329

**Does this PR introduce a user-facing change?**:

- **Is this breaking change**:
- **How to migrate (if breaking change)**:
- **How are users affected by this change**: Fix ECS rollback stage does not remove ECS canary created tasks

### CODE REVIEW

File: pkg/app/piped/executor/ecs/rollback.go [hunk 1]
```diff
@@ -127,12 +127,46 @@ func rollback(ctx context.Context, in *executor.Input, platformProviderName stri
...
+	// Delete Canary taskSet
+	canaryTaskSet, ok := in.MetadataStore.Shared().Get(canaryTaskSetARNKeyName)
+	if !ok {
+		in.LogPersister.Errorf("Unable to restore CANARY task set to clean: Not found")
+		return false
+	}
+	if err = client.DeleteTaskSet(ctx, *service, canaryTaskSet); err != nil {
+		in.LogPersister.Errorf("Failed to remove unused previous PRIMARY taskSet %s: %v", canaryTaskSet, err)
+		return false
+	}
```
Comment (khanhtc1202) [inline pkg/app/piped/executor/ecs/rollback.go:168]: Looks like we tried to clean the canary stub by this part, so how about to reuse `clean` function?
https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/executor/ecs/ecs.go#L349

Comment (khanhtc1202) [inline pkg/app/piped/executor/ecs/rollback.go:168]: Looks like we tried to clean the canary stub by this part, so how about to reuse `clean` function?
https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/executor/ecs/ecs.go#L349

File: pkg/app/piped/executor/ecs/rollback.go [hunk 2]
```diff
@@ -127,12 +127,46 @@ func rollback(ctx context.Context, in *executor.Input, platformProviderName stri
...
+
```
Comment (khanhtc1202) [inline pkg/app/piped/executor/ecs/rollback.go:169]: I think it's safer to do this after L182 (after we finish updating the rollbacked taskset as the primary taskset of the current service and remove the previous primary taskset), since it's more sense to only routing the traffic after primary tasksets are well-prepared and ready to handle incoming requests.

File: pkg/app/piped/executor/ecs/rollback.go [hunk 3]
```diff
@@ -127,12 +127,46 @@ func rollback(ctx context.Context, in *executor.Input, platformProviderName stri
...
+	routingTrafficCfg := provider.RoutingTrafficConfig{
+		{
+			TargetGroupArn: *primaryTargetGroup.TargetGroupArn,
+			Weight:         100,
+		},
+		{
+			TargetGroupArn: *canaryTargetGroup.TargetGroupArn,
+			Weight:         0,
+		},
+	}
```
Comment (khanhtc1202) [inline pkg/app/piped/executor/ecs/rollback.go:146]:
```suggestion
	routingTrafficCfg := provider.RoutingTrafficConfig{
		{
			TargetGroupArn: *primaryTargetGroup.TargetGroupArn,
			Weight:         100,
		},
	}
```
Can we do like this? 🤔

Comment (anhpnv) [reply pkg/app/piped/executor/ecs/rollback.go:146]: - I tried to do like this, but `canaryTargetGroup` not change 🤔 🤔 🤔

image

Comment (ductnn) [reply pkg/app/piped/executor/ecs/rollback.go:146]: - @anhpnv Thanks 🙏

File: pkg/app/piped/executor/ecs/rollback.go (hunk 1 above)
Comment (ductnn) [reply pkg/app/piped/executor/ecs/rollback.go:168]: - Thanks! I'll reuse `clean` function 🙏

File: pkg/app/piped/executor/ecs/rollback.go (hunk 2 above)
Comment (ductnn) [reply pkg/app/piped/executor/ecs/rollback.go:169]: - You're right, it's a secure choice to proceed 🙏

File: pkg/app/piped/executor/ecs/rollback.go (hunk 1 above)
Comment (ductnn) [reply pkg/app/piped/executor/ecs/rollback.go]: @khanhtc1202 I fixed it! [reuse clean function](https://github.com/pipe-cd/pipecd/pull/4465/commits/40c0f29c1893e20dd7e70308cb7e52d4ed5dd46a), please review it 🙏

File: pkg/app/piped/executor/ecs/rollback.go (hunk 2 above)
Comment (ductnn) [reply pkg/app/piped/executor/ecs/rollback.go]: @khanhtc1202 I fixed it! [reuse clean function](https://github.com/pipe-cd/pipecd/pull/4465/commits/40c0f29c1893e20dd7e70308cb7e52d4ed5dd46a), please review it 🙏

File: pkg/app/piped/executor/ecs/rollback.go [hunk 4]
```diff
@@ -147,6 +147,35 @@ func rollback(ctx context.Context, in *executor.Input, platformProviderName stri
...
+
+	currListenerArns, err := client.GetListenerArns(ctx, *primaryTargetGroup)
+	if err != nil {
+		in.LogPersister.Errorf("Failed to get current active listener: %v", err)
```
Comment (khanhtc1202) [inline pkg/app/piped/executor/ecs/rollback.go:164]:
```suggestion
		in.LogPersister.Errorf("Failed to get current active listeners: %v", err)
```
nits

**Review by khanhtc1202 — APPROVED** [review]
Great, thank you 🙌
