### PR TITLE
Fix to use target dsp in script run rollback

### LINKED ISSUE #5214: Can't use the script file on the SCRIPT_RUN_ROLBACK stage
**What happened**:

When using the script file on the `onRollback` field in app.pipecd.yaml, can't execute it on the SCRIPT_RUN_ROLLBACK stage.
PipeCD
(We can use the script file on the SCRIPT_RUN stage when setting the `run` option of this stage)

**file structure**
```
- app.pipecd.yaml
- script.sh
```

**app.pipecd.yaml**
```
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: script-run-like-jenkins
  labels:
    env: example
    team: product
  pipeline:
    stages:
      - name: SCRIPT_RUN
        with:
          run: |
            sleep 10
            sh script.sh
          onRollback: |
            echo $SR_DEPLOYMENT_ID
            echo $SR_APPLICATION_ID
            echo $SR_APPLICATION_NAME
            echo $SR_TRIGGERED_AT
            echo $SR_TRIGGERED_COMMIT_HASH
            echo $SR_REPOSITORY_URL
            echo $SR_SUMMARY
            echo $SR_CONTEXT_RAW
            sh script.sh
```

**What you expected to happen**:

It would be nice to execute the script file when SCRIPT_RUN_ROLLBACK stage is executed.

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does / why we need it**:

Fixed to use TargetDSP on the SCRIPT_RUN_ROLLBACK stage.
With these fixes, we can refer to the files located in the app dir when executing the SCRIPT_RUN_ROLLBACK stage.

I chose TargetDSP, not RunningDSP, because the commands on the `onRollback` are set in app.pipecd.yaml used when Deployment is executed. 
The purpose of the SCRIPT_RUN_ROLLBACK stage is to run whatever command is currently set in onRollback during rollback.

**Which issue(s) this PR fixes**:

Part of #5214

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

File: pkg/app/piped/deploysource/deploysource.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func (p *provider) Get(ctx context.Context, lw io.Writer) (*DeploySource, error)
 
 	if !p.done {
 		p.source, p.err = p.prepare(ctx, lw)
-		p.done = true
+		p.done = p.err == nil // If there is an error, we should re-prepare it next time.
```
Comment (ffjlabo) [inline pkg/app/piped/deploysource/deploysource.go:93]: 📝 This modification is necessary to avoid an error when executing a cancellation while executing TargetDSP.Get in another stage.

I encountered such a situation when canceling the deployment via WebUI during the SCRIPT_RUN stage execution.

Cursor_と_PipeCD__1__png

Comment (ffjlabo) [reply pkg/app/piped/deploysource/deploysource.go]: I split the fixes to the another PR https://github.com/pipe-cd/pipecd/pull/5216

**Review by Warashi — APPROVED** [review]
👍🏻

**Review by t-kikuc — APPROVED** [review]
thank you
