### PR TITLE
Omit long detail comment in actions-plan-preview

### LINKED ISSUE #3224: actions-plan-preview failed to comment the result when its size is too large
**What would you like to be added**:

For example, in the case of using ConfigMap to store large size of text data.

422 Validation Failed [{Resource:IssueComment Field:data Code:unprocessable Message:Body is too long (maximum is 65536 characters)}]

**Why is this needed**:

### PR DESCRIPTION
**Pull request by Hosshii**
**What this PR does / why we need it**:
If the detail comment is too long, omit the detail.
I referred [this comment](https://github.com/pipe-cd/pipecd/issues/3224#issue-1126945517) to determine comment length limit. But it may not be accurate.

**Which issue(s) this PR fixes**:

Fixes #3224

**Does this PR introduce a user-facing change?**:

```release-note
Avoid error from actions-plan-preview when sending a too long message on GitHub
```

### CODE REVIEW

File: dockers/actions-plan-preview/planpreview.go [hunk 1]
```diff
@@ -137,6 +139,12 @@ const (
 	noChangeTitleFormat  = "Ran plan-preview against head commit %s of this pull request. PipeCD detected `0` updated application. It means no deployment will be triggered once this pull request got merged.\n"
 	hasChangeTitleFormat = "Ran plan-preview against head commit %s of this pull request. PipeCD detected `%d` updated applications and here are their plan results. Once this pull request got merged their deployments will be triggered to run as these estimations.\n"
 	detailsFormat        = "<details>\n<summary>Details (Click me)</summary>\n<p>\n\n``` %s\n%s\n```\n</p>\n</details>\n"
+	detailsOmitted       = "Details are too long, so omitted"
```
Comment (nghialv) [inline dockers/actions-plan-preview/planpreview.go:142]:
```suggestion
	detailsOmittedMessage       = "The details are too long to display. Please check the actions log to see full details."
```

Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go:142]: Thank you!

**Comment by Hosshii** [comment]
I fixed!

File: dockers/actions-plan-preview/planpreview.go [hunk 2]
```diff
@@ -170,6 +184,15 @@ func makeCommentBody(event *githubEvent, r *PlanPreviewResult) string {
 		if app.ApplicationKind == "TERRAFORM" {
 			lang = "hcl"
 		}
+
+		l := utf8.RuneCountInString(app.PlanDetails)
+		if detailLen+int64(l) > reservedDetailMessagesLen {
+			fmt.Fprint(&b, detailsOmittedMessage)
```
Comment (nghialv) [inline dockers/actions-plan-preview/planpreview.go:190]: We have to use `fmt.Fprintf(&b, detailsFormat, lang, detailsOmittedMessage)` to ensure that the message is wrapped in the `Details` block.

File: dockers/actions-plan-preview/planpreview.go [hunk 3]
```diff
@@ -170,6 +184,15 @@ func makeCommentBody(event *githubEvent, r *PlanPreviewResult) string {
...
+			detailLen += int64(utf8.RuneCountInString(detailsOmittedMessage))
+			continue
+		}
+
+		detailLen += int64(l)
```
Comment (nghialv) [inline dockers/actions-plan-preview/planpreview.go:195]: Other messages have been added to `b` before so we can use `b.String()` directly to calculate a more accurate value.

```suggestion
                var (
                         msg = app.PlanDetails
                         curLen = utf8.RuneCountInString(b.String())
                		detailsLen = utf8.RuneCountInString(msg)
		)
		if curLen + detailsLen > reservedDetailMessagesLen {
		        msg = detailsOmittedMessage
		}
		fmt.Fprintf(&b, detailsFormat, lang, msg)
```

File: dockers/actions-plan-preview/planpreview.go [hunk 4]
```diff
@@ -208,6 +235,14 @@ func makeCommentBody(event *githubEvent, r *PlanPreviewResult) string {
...
 				lang = "hcl"
 			}
+
+			l := utf8.RuneCountInString(app.PlanDetails)
+			if detailLen+int64(l) > reservedDetailMessagesLen {
+				fmt.Fprint(&b, detailsOmittedMessage)
+				detailLen += int64(utf8.RuneCountInString(detailsOmittedMessage))
+				continue
+			}
+			detailLen += int64(l)
```
Comment (nghialv) [inline dockers/actions-plan-preview/planpreview.go:245]: Same as above.

File: dockers/actions-plan-preview/planpreview.go (hunk 2 above)
Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go:190]: I think it would be redundant to click `Details` block and just see ignored message, so I left out the details tag.
How do you feel about this?

File: dockers/actions-plan-preview/planpreview.go (hunk 3 above)
Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go:195]: At first I was going to do that, but then I decided not to because I might not be able to include all the information in the app if I did.

My plan is to first divide the message into two parts: the detail part and the other part. I assumed that the detail part could be as long as I wanted, but the other parts would not be that long (assumed less than 2000 characters in this pr). Then, I set the limit of the github message to be the part to write the detail, excluding the part to write the other part(So we can write details at most `65536 - 2000` characters, and others at most `2000` characters). This way, no matter how the detail looks like, the other part can always be written (as long as the number of characters in the other part is not exceeded (in this pr this is `2000`)).

File: dockers/actions-plan-preview/planpreview.go (hunk 2 above)
Comment (nghialv) [reply dockers/actions-plan-preview/planpreview.go:190]: Thanks for your explanation. Nice point but I feel that we should wrap it inside the `Details` block to keep the comment layout.

File: dockers/actions-plan-preview/planpreview.go (hunk 4 above)
Comment (nghialv) [inline dockers/actions-plan-preview/planpreview.go:245]: There is no diff in the failure application list so to be simple we don't have to care about them.

File: dockers/actions-plan-preview/planpreview.go (hunk 2 above)
Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go:190]: It's certainly more consistent that way.
I will change the message to be wrapped inside the Detail block.
Thank you!

Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go]: I fixed this in [ae8163e](https://github.com/pipe-cd/pipecd/pull/3253/commits/ae8163e26c2024aa77c471c6af48e960ccaa4f5c). PTAL

File: dockers/actions-plan-preview/planpreview.go (hunk 4 above)
Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go]: fixed in [88266b1](https://github.com/pipe-cd/pipecd/pull/3253/commits/88266b199c4799088301b0374fcf7f8a131c27ce). PTAL

File: dockers/actions-plan-preview/planpreview.go (hunk 3 above)
Comment (nghialv) [reply dockers/actions-plan-preview/planpreview.go]: Thanks for your explanation. I got your point. 👍

File: dockers/actions-plan-preview/planpreview.go [hunk 5]
```diff
@@ -134,9 +136,15 @@ const (
...
-	detailsFormat        = "<details>\n<summary>Details (Click me)</summary>\n<p>\n\n``` %s\n%s\n```\n</p>\n</details>\n"
+	noChangeTitleFormat   = "Ran plan-preview against head commit %s of this pull request. PipeCD detected `0` updated application. It means no deployment will be triggered once this pull request got merged.\n"
+	hasChangeTitleFormat  = "Ran plan-preview against head commit %s of this pull request. PipeCD detected `%d` updated applications and here are their plan results. Once this pull request got merged their deployments will be triggered to run as these estimations.\n"
+	detailsFormat         = "<details>\n<summary>Details (Click me)</summary>\n<p>\n\n``` %s\n%s\n```\n</p>\n</details>\n"
+	detailsOmittedMessage = "The details are too long to display. Please check the actions log to see full details."
+
+	ghMessageLenLimit = 65536
+
+	// Limit of details
+	reservedDetailMessagesLen = ghMessageLenLimit - 2000
```
Comment (nghialv) [inline dockers/actions-plan-preview/planpreview.go:147]:
```suggestion
	detailsLenLimit = ghMessageLenLimit - 5000  # 5000 characters could be used for other parts in the comment message.
```

File: dockers/actions-plan-preview/planpreview.go [hunk 6]
```diff
@@ -200,6 +223,10 @@ func makeCommentBody(event *githubEvent, r *PlanPreviewResult) string {
 	if len(r.FailureApplications) > 0 {
 		fmt.Fprintf(&b, "**An error occurred while building plan-preview for the following applications**\n")
 
+		sort.SliceStable(r.FailureApplications, func(i, j int) bool {
+			return len(r.FailureApplications[i].PlanDetails) < len(r.FailureApplications[j].PlanDetails)
+		})
+
```
Comment (nghialv) [inline dockers/actions-plan-preview/planpreview.go:229]: So this sort will be no longer needed.

File: dockers/actions-plan-preview/planpreview.go (hunk 5 above)
Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go:147]: Thank you!
I change `#` to  `//`

**Comment by Hosshii** [comment]
fixed :)

**Comment by nghialv** [comment]
nit: The release note could be

```
Avoid error from actions-plan-preview when sending a too long message on GitHub
```

File: dockers/actions-plan-preview/planpreview.go [hunk 7]
```diff
@@ -161,6 +168,8 @@ func makeCommentBody(event *githubEvent, r *PlanPreviewResult) string {
 
 	changedApps, pipelineApps, quickSyncApps := groupApplicationResults(r.Applications)
 
+	var detailLen int64
```
Comment (khanhtc1202) [inline dockers/actions-plan-preview/planpreview.go:171]: Not sure why do we need this var of type `int64`, is the `int` type not good enough? If we use `int` we can remove typecasting in the below implementation.

Comment (Hosshii) [reply dockers/actions-plan-preview/planpreview.go:171]: I was wrong; I was confusing int with uint16.
thank you!

**Comment by khanhtc1202** [comment]
Here you go 🙌 
/approve
