### PR TITLE
Fix: Hide version selector on Home page and make v1 default

### LINKED ISSUE #6478: Version selector has inconsistent version on homepage
**What happened**:

The version selector on the homepage shows version (**v1.0.x**). Happening because the template hardcodes a specific index from the versions list. When navigating to the Documentation section, the site redirects to the latest docs version (currently, v0.55.x), and the selector updates correctly there. The homepage and documentation pages display different versions, causing inconsistency. 

Two possible approaches:
1. Show the latest documentation version on the homepage instead of using a hardcoded index.
2. Hide the version selector entirely when on home page.

**What you expected to happen**:

The version selector should be consistent with the actual documentation version, either showing the latest version on the homepage or not appearing there at all.

**How to reproduce it**:

1. Open the homepage.
2. Observe the version selector, it shows **v1.0.x**.
3. Click on Documentation.
4. The selector changes to the latest version.

**Environment**:
- Docs site [pipecd.dev](https://pipecd.dev/)

### PR DESCRIPTION
**Pull request by rahulshendre**
**What this PR does**:

- Hide version selector on the homepage.
- Set docs default to latest, `docs-v1.0`

**Why we need it**:
Homepage was showing a different version than the docs due to hardcoded selector and as v1 is going to be the latest version, we need it to be the default.

**Which issue(s) this PR fixes**:

Fixes #6478

### CODE REVIEW

**Comment by rahulshendre** [comment]
@eeshaanSA, PTAL when you have time : )

File: docs/main.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ import (
 const dir = "/public"
 
 // Don't update here manually. /hack/gen-release-docs.sh does.
```
Comment (eeshaanSA) [inline docs/main.go:30]: Pretty self explanatory, isnt it? 👀

Comment (rahulshendre) [reply docs/main.go:30]: I did see the comment, but noticed that latestPath was manually updated in the v0.55.0 release (commit bc3d5e0 in docs/main.go #6298 by @khanhtc1202 ) when changing from v0.54.x to v0.55.x.

Since v1.0.x already exists in config.toml, the script exits early and doesn't update latestPath. So manual edit seems to be the standard approach for updating the latest version when it already exists.

Comment (eeshaanSA) [reply docs/main.go:30]: I see, I will have to check on that. But your theory makes sense.

**Comment by rahulshendre** [comment]
@eeshaanSA, there is one more thing I noticed. On smaller screens (phones), the version selector is not visible, so users currently have no way to change the version.

Earlier users landed on v0.55, but after this PR they will land on v1 docs by default. However, on mobile they still won’t be able to switch versions since the selector is hidden.

After we get this PR is merged, I’ll open a separate issue for this.

File: docs/main.go (hunk 1 above)
Comment (rahulshendre) [reply docs/main.go:30]: Great, thanks

**Review by eeshaanSA — CHANGES_REQUESTED** [review]
@rahulshendre, while workflows are being run, can you provide a detailed screen recording of the change? Sorry for the trouble, but we do not have a live preview.

**Comment by rahulshendre** [comment]
> @rahulshendre, while workflows are being run, can you provide a detailed screen recording of the change? Sorry for the trouble, but we do not have a live preview.

Sure @eeshaanSA
Here you go. Screen recording below.

https://github.com/user-attachments/assets/e6d25b57-5473-42e8-add0-ccaa460a2dfc

**Review by eeshaanSA — APPROVED** [review]
LGTM
