### PR TITLE
Update containerd config to fix ImagePullBackOff error

### LINKED ISSUE #3152: `make kind-up` cause ImagePullBackOff error
**What happened**:
I get ImagePullBackOff error in some pods when I run the `make kind-up` following this [control-plain docs](https://pipecd.dev/docs/contribution-guidelines/control-plane-development/).

**What you expected to happen**:
all pods works correctly

**How to reproduce it**:
run `make kind-up` command

**Environment**:
- `piped` version: None
- `control-plane` version: 0.24
- Others:

### PR DESCRIPTION
**Pull request by Hosshii**
**What this PR does / why we need it**:
Currently, `make kind-up` uses `plugins."io.containerd.grpc.v1.cri".registry.mirrors` to configure local image registry. However, this is [deprecated](https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-image-registry) and causes ImagePullBackOff error.
To fix this, update registry configs to use `plugins."io.containerd.grpc.v1.cri".registry`, set `config_path`, and add `hosts.toml` file. ([registry configuration docs](https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration))

**Which issue(s) this PR fixes**:

Fixes #3152

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: hack/create-kind-cluster.sh [hunk 1]
```diff
@@ -46,18 +46,39 @@ if [ "${running}" != 'true' ]; then
...
+[host.\"http://${REG_NAME}:${REG_PORT}\"]
+  capabilities = [\"pull\", \"resolve\", \"push\"]
+  skip_verify = true
+  plain-http = true
+EOF
+systemctl restart containerd
+"
+
 # Connect the registry to the cluster network
 # (the network may already be connected)
```
Comment (nghialv) [inline hack/create-kind-cluster.sh:81]: Move its comment to L59.

**Comment by nghialv** [comment]
You make my day! 💯 
I have just left a nit. Please fix it then

/lgtm

File: hack/create-kind-cluster.sh (hunk 1 above)
Comment (Hosshii) [reply hack/create-kind-cluster.sh]: I missed it. thank you!

**Comment by Hosshii** [comment]
I fixed!

**Comment by khanhtc1202** [comment]
Nice 🙌 
/approve

**Comment by nghialv** [comment]
Great job!
/lgtm
