### PR TITLE
Handle declared type

### LINKED ISSUE #3494: [FILEDB] Unable to filter correctly if the value passed through filter.Value is declared type
**What happened**:

The current implementation for filter logic requires casting filter.Value (if type interface{}) to some comparable type before performing. We're using `val.(type)` and a switch case block to handle casting value based on its type (ref [compare logic](https://github.com/pipe-cd/pipecd/blob/master/pkg/datastore/filedb/filter.go#L97-L109)). The problem is for declared type (generated by protobuf for enum, `type model.XYZ int32`), there will be no defined cases for all alias types (for instance, type `model.ApplicationKind` is an alias to type int32, but only type int32 is handled)

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Previously, for queries of kind
```go
{
	Field:    "Kind",
	Operator: datastore.OperatorEqual,
	Value:    model.ApplicationKind_KUBERNETES,
}
```
the filter logic of filedb will return false event the model object is of has field Kind of the same value. That is caused by the unmarshaled model object only contains primitive types (to keep filedb layer generic, only case raw byte of models to map[string]interface{}, not it true type), and the operand value from queries is of its wrapped type (for instance `model.ApplicationKind`). As the result, comparing those two values will return `(mismatched type model.ApplicationKind and float64)` error. This PR provides logic to convert types which not a primitive type of filter.Value to primitive types, so the filter compare logic could work.

**Which issue(s) this PR fixes**:

Fixes #3494 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/datastore/filedb/filter.go [hunk 1]
```diff
@@ -220,3 +225,32 @@ func normalizeFieldName(key string) string {
...
+
+// normalizeFieldValue converts value of any type to the primitive type
+// Note: Find a better way to handle this instead of marshal/unmarshal.
+func normalizeFieldValue(val interface{}) (interface{}, error) {
+	var needConvert = false
+	switch val.(type) {
+	case int, int8, int16, int32, int64:
+	case uint, uint8, uint16, uint32:
+	case float32, float64:
+	case string:
```
Comment (khanhtc1202) [inline pkg/datastore/filedb/filter.go:237]:
```suggestion
	case string:
	case bool:
```

**Comment by nghialv** [comment]
👍 

/lgtm

**Review by knanao — COMMENTED** [review]
Looks good.
/approve
