### PR TITLE
Fix unable to plan deployment in case of changing app config

### LINKED ISSUE #3686: Unable to plan deployment in case of changing application config input
**What happened**:

In case the application configuration input is changed (input section) the application of kind K8s will be failed with `Unable to plan the deployment` error

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version: 0.32.0
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3686 

**Does this PR introduce a user-facing change?**:

```release-note
Fix unable to plan deployment in case of changing configuration of kind Kubernetes application
```

### CODE REVIEW

File: pkg/app/piped/planner/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -200,7 +200,12 @@ func (p *Planner) Plan(ctx context.Context, in planner.Input) (out planner.Outpu
 			return
 		}
 
-		loader := provider.NewLoader(in.ApplicationName, runningDs.AppDir, runningDs.RepoDir, in.GitPath.ConfigFilename, cfg.Input, in.GitClient, in.Logger)
+		runningCfg := runningDs.ApplicationConfig.KubernetesApplicationSpec
+		if runningCfg == nil {
```
Comment (knanao) [inline pkg/app/piped/planner/kubernetes/kubernetes.go:204]: Sorry, I couldn't understand this meaning.
What happens with the first plan?

Comment (khanhtc1202) [reply pkg/app/piped/planner/kubernetes/kubernetes.go:204]: cfg.Input is the application configuration of the target commit (the one which we're going to deploy), but at that place what we need is the currently running application configuration, that is why I pull runningCfg there

ref: https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/planner/kubernetes/kubernetes.go#L56-L65

Comment (knanao) [reply pkg/app/piped/planner/kubernetes/kubernetes.go:204]: Oh, I totally get it.
I misunderstood the application manifest and application config.
Thank you.

**Review by knanao — APPROVED** [review]

**Review by nghialv — APPROVED** [review]
Nice catch!
