### PR TITLE
Fix unable to load manifest for PlanPreview in case of ECS standalone tasks

### LINKED ISSUE #5370: [ECS] PlanPreview of standalone tasks failed
**What happened**:

PlanPreview for ECS standalone tasks failed with the following error:

```
failed to load ecs manifests at the head commit (read /tmp/plan-preview-builder-xxx/deploysource3xxxx/repo-xxx/xxx/xxx: is a directory)
```

**What you expected to happen**:

Not failed and only TaskDefinitions are compared.

**How to reproduce it**:

1. ADD an application of an ECS standalone task
2. Create a PullRequest with diff of the standalone task
3. Call PlanPreview

**Environment**:
- `piped` version: v0.49.4
- `control-plane` version: v.049.4
- Others:

**The cause**

Currently, PlanPreview for ECS tries to load both serviceDef and taskDef.
However, standalone tasks don't have serviceDef.
That's why, all PlanPreview for ECS standalone tasks will fail.

https://github.com/pipe-cd/pipecd/blob/57f0672d34a907e1d13ff6b2f45e66ae973f9fe9/pkg/app/piped/planpreview/ecsdiff.go#L41-L45

### PR DESCRIPTION
**Pull request by cuongvd23**
**What this PR does**:

Skip load `serviceDef` on the ECS standalone task since there is no `serviceDef` file while running planpreview logic

**Why we need it**:

**Which issue(s) this PR fixes**:

Fixes #5370

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Review by khanhtc1202 — APPROVED** [review]
Good catch 👍

File: pkg/app/piped/planpreview/ecsdiff.go [hunk 1]
```diff
@@ -20,6 +20,7 @@ import (
 	"fmt"
 	"io"
 
+	"github.com/aws/aws-sdk-go-v2/service/ecs/types"
```
Comment (t-kikuc) [inline pkg/app/piped/planpreview/ecsdiff.go:23]:
```suggestion
	"github.com/aws/aws-sdk-go-v2/service/ecs/types"
	
```

**Review by t-kikuc — APPROVED** [review]
It worked well, thank you!
image
