### PR TITLE
Handle ECS Apps DeploymentConfiguration and containers Environments drift detection

### LINKED ISSUE #5336: Drift Detection Issue with ECS Apps
**What happened**:

After upgrading PipeCD to v0.49.3, all ECS applications in the PipeCD console are displayed as "Out Of Sync". 
The detected drift includes:
- Configuration settings that are not specified in the `servicedef.yaml` file.
- Environment variables that have not been changed but are still flagged as differences.

**What you expected to happen**:

- Unchanged environment variables should not be flagged as drift.
- Drift detection should only report differences for properties explicitly managed by `servicedef.yaml`
- Configuration settings not specified in `servicedef.yaml` should be ignored by the drift detection process.

**How to reproduce it**:

- Navigate to the PipeCD console and view any ECS application.
- Notice that all ECS applications are marked as "Out Of Sync".
- Inspect the detected diff to see unexpected changes.

**Environment**:
- `piped` version: v0.49.3
- `control-plane` version:
- Others:

**Potential Cause**

The issue is likely due to the incorrect handling of the order of environment variables.

**Caution Notes** (advised from @t-kikuc)
- service.DeploymentConfiguration: 
  - If `head` is nil, then `live` should also be set to nil. This is to prevent issues caused by unexpected default values. 
  - Add an item to the func comment. (Under `TODO: Maybe we should check diff of following fields`)
- environment
  - Make sure to sort both live and head environment variables. There’s a possibility that this behaviour might change in the future, so it’s important to handle this now.
  - It’s recommended that the sorting logic be extracted into a separate function, for example: `func sortKeyPairs(kps []types.KeyValuePair)`
  - When sorting, use slices.Clone() to create a copy of the Environment array before performing operations. This prevents modifications to the original array, which could otherwise cause issues in the PlanPreview process.

### PR DESCRIPTION
**Pull request by HoangNguyen689**
**What this PR does**:

**Why we need it**:

**Which issue(s) this PR fixes**:

Fixes #5336

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

File: pkg/app/piped/driftdetector/ecs/detector.go [hunk 1]
```diff
@@ -480,3 +497,13 @@ func ignoreAutoScalingDiff(r *provider.DiffResult) bool {
 		r.New.ServiceDefinition.DesiredCount == 0 && // When desiredCount is 0 or not defined in the head manifest, autoscaling may be enabled.
 		r.Old.ServiceDefinition.DesiredCount != r.New.ServiceDefinition.DesiredCount
 }
+
+func sortKeyPairs(kps []types.KeyValuePair) []types.KeyValuePair {
+	sorted := make([]types.KeyValuePair, len(kps))
+	copy(sorted, kps)
```
Comment (t-kikuc) [inline pkg/app/piped/driftdetector/ecs/detector.go:503]: How about cloning here and removing `slices.Clone` when calling? That will reduce copying slices.

```suggestion
	sorted := slices.Clone(kps)
```

We can notice this function won't have side effects from a caller side because it returns slices.

File: pkg/app/piped/driftdetector/ecs/detector.go [hunk 2]
```diff
@@ -316,6 +327,12 @@ func ignoreParameters(liveManifests provider.ECSManifests, headManifests provide
 			// Essential is true by default. See https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-es.
 			cd.Essential = aws.Bool(true)
 		}
+
+		// Sort the head environment variables by name.
+		envs := slices.Clone(cd.Environment)
+		envs = sortKeyPairs(envs)
+		cd.Environment = envs
```
Comment (t-kikuc) [inline pkg/app/piped/driftdetector/ecs/detector.go:334]: After refactoring `sortKeyPairs()`

```suggestion
		cd.Environment = sortKeyPairs(cd.Environment)
```

File: pkg/app/piped/driftdetector/ecs/detector.go [hunk 3]
```diff
@@ -299,6 +305,11 @@ func ignoreParameters(liveManifests provider.ECSManifests, headManifests provide
 		liveService.NetworkConfiguration = &types.NetworkConfiguration{AwsvpcConfiguration: &awsvpcCfg}
 	}
 
+	// Ignore the diff of DeploymentConfiguration if it's not specified.
```
Comment (t-kikuc) [inline pkg/app/piped/driftdetector/ecs/detector.go:308]: Would you add `- service.DeploymentConfiguration` to the function's comment?

```go
// TODO: Maybe we should check diff of following fields when not set in the head manifests in some way. Currently they are ignored:
//   - service.DeploymentConfiguration                   <--------- HERE
//   - service.PlatformVersion
//   - service.RoleArn
func ignoreParameters(liveManifests provider.ECSManifests, headManifests provider.ECSManifests) (live, head provider.ECSManifests) {
```

Comment (HoangNguyen689) [reply pkg/app/piped/driftdetector/ecs/detector.go]: added in https://github.com/pipe-cd/pipecd/pull/5344/commits/930b46fc7f1fdf5523793cb7d503330cbdd6e7bb

File: pkg/app/piped/driftdetector/ecs/detector.go (hunk 1 above)
Comment (HoangNguyen689) [reply pkg/app/piped/driftdetector/ecs/detector.go]: fixed in https://github.com/pipe-cd/pipecd/pull/5344/commits/930b46fc7f1fdf5523793cb7d503330cbdd6e7bb

**Review by t-kikuc — APPROVED** [review]

**Review by ffjlabo — APPROVED** [review]
Thank you for the contribution!
